name: auto-pull-merge

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
      - synchronize
      - edited
  check_suite:
    types:
      - completed


jobs:
  autopull:
    if: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message, ' '), '#pull') }}
    runs-on: ubuntu-latest
    steps:
      - uses: devops-infra/action-pull-request@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: "auto-pull from commit '${{ github.event.head_commit.message }}'"
          label: automerge
    
  automerge:
    if: ${{ github.event_name != 'push' }}
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: pascalgn/automerge-action@v0.15.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}