name: auto-pull-merge

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
      - synchronize
      - edited
  check_suite:
    types:
      - completed


jobs:
  autopull:
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, '#pull') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.PAT }}
          destination_branch: ${{ github.event.repository.default_branch }}
          pr_title: "auto-pull from commit '${{ github.event.head_commit.message }}'"
          pr_label: "automerge"
    
  automerge:
    if: ${{ github.event_name != 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Automerge
        uses: pascalgn/automerge-action@v0.15.3
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          