name: test

on:
  pull_request:
    branches: [master]
    types: [opened]


jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"